kind: pipeline
name: default

steps:
- name: hadolint
  image: hadolint/hadolint:latest-debian
  commands:
    - hadolint --version
    - hadolint  Dockerfile
- name: docker  
  image: plugins/docker
  settings:
    repo: docker.eighty-three.me:5000/tuxpeople/debugcontainer
    registry: docker.eighty-three.me:5000
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password
- name: notify
  image: drillster/drone-email
  host: mail
  from: drone@eighty-three.me
  recipients: [ thomas@tuxpeople.org ]
  subject: >
    [{{ build.status }}]
    {{ repo.owner }}/{{ repo.name }}
  template: >
    https://git.io/vgvPz
  when:
    status: [ success, changed, failure ]
