kind: pipeline
name: default

test:
- name: hadolint
  image: hadolint/hadolint:latest-debian
  commands:
    - hadolint --version
    - hadolint  Dockerfile
    
build:
- name: docker  
  image: plugins/docker
  settings:
    repo: docker.eighty-three.me:5000/tuxpeople/debugcontainer
    registry: docker.eighty-three.me:5000
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password

notify:
  image: drillster/drone-email
  environment:
    - DOCKER_LAUNCH_DEBUG=true
  host: mail
  from: drone@eighty-three.me
  subject: >
    [{{ build.status }}]
    {{ repo.owner }}/{{ repo.name }}
  template: >
    https://git.io/vgvPz
  when:
    status: [ success, changed, failure ]
