kind: pipeline
name: default

steps:
- name: hadolint
  image: hadolint/hadolint:latest-debian
  ignored:
    - DL3025
  commands:
    - hadolint --version
    - hadolint  Dockerfile
- name: docker  
  image: plugins/docker
  settings:
    repo: docker.eighty-three.me:5000/tuxpeople/debugcontainer
    registry: docker.eighty-three.me:5000
    auto_tag: true
    username:
      from_secret: username
    password:
      from_secret: password
